const friendsData = [
  {
    name: "AAKARSH DIVYAM",
    photo: "images/aakarsh.png",
    usn: "1CR22CS001",
    branch: "CSE",
    tenth: "86.0%",
    twelfth: "76.0%",
    cgpa: "7.84",
    emailid: "aadi22cs@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A3 C4 P3.5 S3 Level: 3",
    linkedIn: "https://www.linkedin.com/in/aakarsh-divyam-291512309",
    github: "https://github.com/ChillyColor"
  },
  {
    name: "ANANT KUMAR GUPTA",
    photo: "images/anant.png",
    usn: "1CR22CS019",
    branch: "CSE",
    tenth: "90.40%",
    twelfth: "82.80%",
    cgpa: "8.74",
    emailid: "angu22cs@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A3 C4 P4 S3 Level: 3",
    linkedIn: "https://www.linkedin.com/in/anant-kumar-268346244",
    github: "https://github.com/im47ak"
  },
  {
    name: "JAYANT RAJ",
    photo: "images/jayant.png",
    usn: "1CR22IS062",
    branch: "ISE",
    tenth: "69.83%",
    twelfth: "70.33%",
    cgpa: "6.75",
    emailid: "jara22ise@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A3 C2 P4 S3 Level: 3",
    linkedIn: "https://www.linkedin.com/in/jayant-rajb43499330",
    github: "https://github.com/jayant200803"
  },
  {
    name: "MAHENDER SINGH",
    photo: "images/mahender.png",
    usn: "1CR22IS079",
    branch: "ISE",
    tenth: "84.4%",
    twelfth: "92.0%",
    cgpa: "8.59",
    emailid: "masi22ise@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A4 C4 P4 S3 Level: 4",
    linkedIn: "https://www.linkedin.com/in/mahender-singh-1406h",
    github: "https://github.com/Mahi014"
  },
  {
    name: "NIHAL KUMAR",
    photo: "images/nihal.png",
    usn: "1CR22CD029",
    branch: "CS-DS",
    tenth: "78.4%",
    twelfth: "70.0%",
    cgpa: "8.46",
    emailid: "niku22csds@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A4 C4 P4 S3 Level: 4",
    linkedIn: "https://www.linkedin.com/in/thisisnihal",
    github: "https://github.com/thisisnihal"
  },
  {
    name: "RATNESH VAIBHAV PANDEY",
    photo: "images/ratnesh.png",
    usn: "1CR22IS113",
    branch: "ISE",
    tenth: "84.0%",
    twelfth: "69.2%",
    cgpa: "9.17",
    emailid: "rapa22ise@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A3 C4 P4 S3 Level: 3",
    linkedIn: "https://www.linkedin.com/in/ratnesh-vaibhav-pandey-502570154",
    github: "https://github.com/Ratnesh433"
  },
  {
    name: "RAUNAK MISHRA",
    photo: "images/raunak.png",
    usn: "1CR22EC185",
    branch: "ECE",
    tenth: "69.5%",
    twelfth: "59.6%",
    cgpa: "6.69",
    emailid: "rami22ece@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A0 C4 P3.5 S3 Level: 3",
    linkedIn: "https://www.linkedin.com/in/raunak-mishra-185a801b2",
    github: "N/A"
  },
  {
    name: "U VIKRAM",
    photo: "images/vikram.png",
    usn: "1CR22CD052",
    branch: "CS-DS",
    tenth: "83.4%",
    twelfth: "95.8%",
    cgpa: "9.03",
    emailid: "uvi22csds@cmrit.ac.in",
    company: "N/A",
    role: "N/A",
    package: "N/A",
    placementType: "N/A",
    status: "Not Placed",
    tylLevel: "L4 A3 C4 P3.5 S3 Level: 3",
    linkedIn: "https://www.linkedin.com/in/u-vikram-270a44258",
    github: "https://leetcode.com/u/Vicky_1403"
  }
];
